# Pytorch Basics

> referecence: [Pytorch Official Documentation](https://docs.pytorch.org/tutorials/beginner/basics/intro.html)

## Tensors
Tensors and NumPy arrays share the same underlying memory, eliminating the data copy.

### Initialize a tensor

In [10]:
import torch
import numpy as np

In [11]:

data = [[1,2], [3,4]]
# From data
x_data = torch.tensor(data)
print("x_data:\n", x_data)

# From a NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print("x_np:\n", x_np)

# From another tensor
x_ones = torch.ones_like(x_data)
print("x_ones:\n", x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print("x_rand:\n", x_rand)

# With random or constant values
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
full_tensor = torch.full(shape, float('-inf'))

print("full_tensor:\n", full_tensor)


x_data:
 tensor([[1, 2],
        [3, 4]])
x_np:
 tensor([[1, 2],
        [3, 4]])
x_ones:
 tensor([[1, 1],
        [1, 1]])
x_rand:
 tensor([[0.7924, 0.5381],
        [0.0795, 0.5060]])
full_tensor:
 tensor([[-inf, -inf, -inf],
        [-inf, -inf, -inf]])


### Operations on Tensors
 Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

### Bridge with Numpy
Tensors on the CPU and Numpy arrays can share their underlying memory locations, and changing one will change the other.

In [12]:
# We move our tensor to the current accelerator if available
t = torch.ones(4, 4)
n = t.numpy()
print(f"t: {t}")
print(f"n: {n}")
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")


t: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
n: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
t: tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
n: [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [13]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


## Datasets and DataLoaders

Pytorch provides two data primitives: `torch.utils.data.DataLoader` and `torch.utils.data.Dataset`.
`Dataset` stores the samples and their corresponding labels, and `DataLoader` wraps an iterable around the `Dataset` to enable easy access to the samples.

### Loading a Dataset
Pytorch domain libraries provide a number of pre-loaded datasets.
We can index `Datasets` manually like a list: `training_data[index]`

In [14]:
import torch
from torch.utils.data import Dataset
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt


training_data = datasets.FashionMNIST(
    root="/data2/huhu_data/download",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

 13%|█▎        | 3.47M/26.4M [04:14<28:04, 13.6kB/s]


KeyboardInterrupt: 