# Pytorch Basics

> referecence: [Pytorch Official Documentation](https://docs.pytorch.org/tutorials/beginner/basics/intro.html)

## Tensors
Tensors and NumPy arrays share the same underlying memory, eliminating the data copy.

### Initialize a tensor

In [1]:
import torch
import numpy as np


In [2]:

data = [[1,2], [3,4]]
# From data
x_data = torch.tensor(data)
print("x_data:\n", x_data)

# From a NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print("x_np:\n", x_np)

# From another tensor
x_ones = torch.ones_like(x_data)
print("x_ones:\n", x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print("x_rand:\n", x_rand)

# With random or constant values
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
full_tensor = torch.full(shape, float('-inf'))

print("full_tensor:\n", full_tensor)


x_data:
 tensor([[1, 2],
        [3, 4]])
x_np:
 tensor([[1, 2],
        [3, 4]])
x_ones:
 tensor([[1, 1],
        [1, 1]])
x_rand:
 tensor([[0.9815, 0.2415],
        [0.0402, 0.8662]])
full_tensor:
 tensor([[-inf, -inf, -inf],
        [-inf, -inf, -inf]])
